### ISSUE TITLE
Binary protocol is uncompatible with the Server connected

### ISSUE THREAD

**Issue by rb2k** [aemadrid/orientdb-jruby#1]
WIth 0.1.6 and OrientDB 0.9.25 
db = OrientDB::DocumentDatabase.connect "remote:localhost/somedb", 'root', 'password'

```
$ ruby orientdb-import.rb 
com.orientechnologies.orient.enterprise.channel.binary.ONetworkProtocolException: Binary protocol is uncompatible with the Server connected: client=2, server=3
at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryProtocol.checkProtocolVersion(OChannelBinaryProtocol.java:80)
at com.orientechnologies.orient.client.remote.OStorageRemote.createNetworkConnection(OStorageRemote.java:1107)
at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1008)
at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:104)
at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:88)
at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:44)
at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:98)
at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:542)
at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:392)
at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:68)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:302)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:173)
at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:103)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:276)
at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:322)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:207)
at orientdb_minus_import.__file__(orientdb-import.rb:6)
at orientdb_minus_import.load(orientdb-import.rb)
at org.jruby.Ruby.runScript(Ruby.java:671)
at org.jruby.Ruby.runNormally(Ruby.java:575)
at org.jruby.Ruby.runFromMain(Ruby.java:424)
at org.jruby.Main.doRunFromMain(Main.java:278)
at org.jruby.Main.internalRun(Main.java:198)
at org.jruby.Main.run(Main.java:164)
at org.jruby.Main.run(Main.java:148)
at org.jruby.Main.main(Main.java:128)
```

NativeException: com.orientechnologies.orient.core.exception.ODatabaseException: Can't open database
  connect at /Users/xxxxxxx/.rvm/gems/jruby-head/gems/orientdb-0.0.16-java/lib/orientdb/database.rb:98
   (root) at orientdb-import.rb:6

**Comment by rb2k** [comment]
Noticed that the jars were outdated, sent a pull request
